// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/page-echarts/src/bar-echart.vue')['default']
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElAvatar: typeof import('element-plus/es/el-avatar')['default']
    ElBreadcrumb: typeof import('element-plus/es/el-breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-plus/es/el-breadcrumb-item')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import('element-plus/es/el-card')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElConfigProvider: typeof import('element-plus/es/el-config-provider')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElDropdown: typeof import('element-plus/es/el-dropdown')['default']
    ElDropdownItem: typeof import('element-plus/es/el-dropdown-item')['default']
    ElDropdownMenu: typeof import('element-plus/es/el-dropdown-menu')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElLink: typeof import('element-plus/es/el-link')['default']
    ElMain: typeof import('element-plus/es/el-main')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    ElTabPane: typeof import('element-plus/es/el-tab-pane')['default']
    ElTabs: typeof import('element-plus/es/el-tabs')['default']
    LineEchart: typeof import('./src/components/page-echarts/src/line-echart.vue')['default']
    MapEchart: typeof import('./src/components/page-echarts/src/map-echart.vue')['default']
    NavHeader: typeof import('./src/components/nav-header/src/nav-header.vue')['default']
    NavMenu: typeof import('./src/components/nav-menu/src/nav-menu.vue')['default']
    PageContent: typeof import('./src/components/page-content/src/page-content.vue')['default']
    PageModal: typeof import('./src/components/page-modal/src/page-modal.vue')['default']
    PageSearch: typeof import('./src/components/page-search/src/page-search.vue')['default']
    PieEchart: typeof import('./src/components/page-echarts/src/pie-echart.vue')['default']
    RoseEchart: typeof import('./src/components/page-echarts/src/rose-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/nav-header/src/user-info.vue')['default']
  }
}

export {}
